### ISSUE TITLE
Can't sanitize binding "ubuntu-fs" when starting box86

### ISSUE THREAD

**Issue by Miepee** [Herick75/Box4Droid#10]
The install script works fine, but after trying to start box86 via `start-box86`, I get the following error:
```
ls: cannot access 'ubuntu-binds': No such file or directory
proot warning: can't sanitize binding 'ubuntu-fs': No such file or directory
fatal error: see `proot --help`.
```

**Comment by Miepee** [comment]
So it seems like it's failing with `ls -A ubuntu-binds`. Strangely enough, when I just execute that command normally, it returns an exit code of 0 (i.e. directory exists)

**Comment by Herick75** [comment]
Fixed
