### ISSUE TITLE
Stuck on "Loading preferences from config files, please wait"

### ISSUE THREAD

**Issue by Fl4shb4ng** [Herick75/Box4Droid#11]
Poco F3
Android 13
VoltageOS
Immesity Kernel

**Comment by SombraShadow** [comment]
Did you type "x11" before? because with me, Wine already appears in the termux 11 when this sentence appears.

**Comment by Fl4shb4ng** [comment]
Yes, I tried that but I get a black screen on x11

**Comment by SombraShadow** [comment]
Oh,well I believe it's some bug involving the custom rom, but only herick to say for sure.

**Comment by Fl4shb4ng** [comment]
What rom do you have??

**Comment by SombraShadow** [comment]
I use Stock Rom
My specs:
Moto G9 Plus
Android 11 (Stock)
Kernel (Stock)

**Comment by SolusMonahus** [comment]
Similar problem.
OnePlus 9r
Android 12(custom)
Nameless OS
Kernel (Nameless)
Magisk

**Comment by Herick75** [comment]
New version of Rootfs are released,please update

**Comment by Herick75** [comment]
Box4Droid 0.0.3 stable released, install and try again
