### ISSUE TITLE
Multiarch to box86/box64 in one rootfs (Suggestion)

### ISSUE THREAD

**Issue by Ilya114** [Herick75/Box4Droid#15]
Hi, I know you using armhf rootfs to use box86 in arm64 phones, but, we can use multiarch to use box86 and box64 in one rootfs, you can see the installation instruction, in my [repo](https://github.com/Ilya114/box86-64-termux). You have Telegram to contact with you?

**Comment by Ilya114** [comment]
I`m will try modify rootfs to add box64 and i need to fix termux-x11 not work

**Comment by Herick75** [comment]
Hello, thank you very much for your suggestion. I am already using a Rootfs arm64 with multiarch, however I only installed Box86 as I am having some problems when using amd64 Wine Versions with Box64 between Versions 6.17-7.22, only the versions 8 and up work. I used the precompiled versions of PlayOnLinux, but I will test other builds (Like the Kron4ek builds).  You can find me in my project group, the link is [here.](https://t.me/Box86BR)

**Comment by Herick75** [comment]
> I`m will try create new rootfs to add box64 and i need to fix not working termux-x11

What version of Termux-x11 are you using?

**Comment by Ilya114** [comment]
> > I`m will try create new rootfs to add box64 and i need to fix not working termux-x11
> 
> What version of Termux-x11 are you using?

From your repo, I'm fixed it when mounted /tmp from Termux. Also I have Mesa not working, only 22.x working
