### ISSUE TITLE
forked Ilya114 Box4Droid issue launching x11

### ISSUE THREAD

**Issue by Luihart** [Herick75/Box4Droid#18]
After running Script and trying start x11 it gives an Error:
/data/data/com.termux/files/usr/bin/x11: line 1: 404:: command not found

**Comment by SolusMonahus** [comment]
![Screenshot_20230421-232221_Termux](https://user-images.githubusercontent.com/113862634/233728150-db5c4f8b-13a7-480c-95d4-cdbc1cd38fae.png)

**Comment by SolusMonahus** [comment]
@Luihart Wrote to file x11:
#!/bin/bash

while true; do
clear
echo " Por favor, selecione uma resolucão para o Xvfb :"
echo ""
echo " Please select a resolution for Xvfb :"
echo ""
echo ""
echo "1)640x480 (4:3)"
echo "2)800x600 (4:3)"
echo "3)1024x768 (4:3)"
echo "4)1280x720 (16:9)"
echo "5)1920x1080 (16:9)"
echo "6)1400x600 (7:3)"
echo "7)2560x1600 (16:10)"


echo ""
echo ""
echo " A resolução 1400x600 consegue se adequar a proporção da tela do celular,para usar ela corretamente entre nas configurações do Termux-x11, e em "Display resolution mode" coloque em "scaled" e coloque em 160%.Não se esqueça de colocar a mesma resolução no arquivo Box86.conf "
echo ""
echo " The 1400x600 resolution manages to adapt to the proportion of the cell phone screen, to use it correctly enter the Termux-x11 settings, and in "Display resolution mode" set it to "scaled" and set it to 160%.Don't forget to set the same resolution in the Box86.conf file "
echo ""
    read -p " ..." option

    case $option in
        [1]* ) export res=640x480x24;break;;
        [2]* ) export res=800x600x24;break;;
	[3]* ) export res=1024x768x24;break;;
	[4]* ) export res=1280x720x24;break;;
	[5]* ) export res=1920x1080x24;break;;
	[6]* ) export res=1400x600x24;break;;
        [7]* ) export res=2560x1600x24;break;;
    esac
done
echo $res
DISPLAY=:1 termux-x11 &>/dev/null & env DISPLAY=:1 Xvfb -listen tcp :1 -ac -screen 0 $res &>/dev/null & pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1 &>/dev/null
clear
echo ""
echo -e "Termux-x11 iniciado."
echo ""
echo -e "Termux-x11 started."

**Comment by Ilya114** [comment]
Currently, repo not finished, I'm will fix today

**Comment by SolusMonahus** [comment]
@Ilya114 black screen after command start-box86

**Comment by Ilya114** [comment]
> @Ilya114 black screen after command start-box86

Press Ctrl+C, write box86 wine explorer and show me output

**Comment by Herick75** [comment]
I think everything is fixed now
