### ISSUE TITLE
proot warning

### ISSUE THREAD

**Issue by xXTopaz** [Herick75/Box4Droid#20]
I have updated but still recieving this error trying to run The Sims 2 Ultimate Collection

./ptrace/user.h:46: word_t convert_user_offset(word_t): assertion "0" failed
proot warning: signal 6 received from process 24665

**Comment by Presx2FForRespect** [comment]
me too with warcraft 3

**Comment by Herick75** [comment]
It's related to Phantom Process Killer, disable it or use chroot mode(Requires root)
