### ISSUE TITLE
TFM.exe Trojan in rootfs

### ISSUE THREAD

**Issue by Alea-iactaest** [Herick75/Box4Droid#21]
The file TFM.exe in location \proot-distro\installed-rootfs\ubuntu\opt\TFM.exe gives the following result in virustotal.

https://www.virustotal.com/gui/file/f96b1d8fcf19c95f1634f226347410c83798a726774abbcd2baf4e34bfa4b7e7

So, this file seems like a virus and I wanted to know what it does.

**Comment by Ilya114** [comment]
You can replace it to original TFM from GitHub (It has only 2 false detect, you can check source code if you not sure): https://github.com/radzikpwnz/tfm/releases/download/v1.0.1/TFM.exe

**Comment by Herick75** [comment]
Thanks also for notifying me about this, I will replace this TFM with the original one

**Comment by Herick75** [comment]
Thanks also for notifying me about this, I will replace this TFM with the original one
