### ISSUE TITLE
BioShock (2007) takes too much time to load, and crashes at the first 3D scene

### ISSUE THREAD

**Issue by yuraPIMENOV** [Herick75/Box4Droid#29]
The game BioShock (2007) takes too much time to boot up (5-7 min), the intro level also takes too much time to load, and then crashes.

**Comment by SolusMonahus** [comment]
@yuraPIMENOV This is fine. Run with key -dx9

**Comment by yuraPIMENOV** [comment]
> @yuraPIMENOV This is what happens when you start dx10. Run with key -dx9

I installed the game to C:, launched it with -dx9 - but it still boots up as slow as GTA 5 without SSD, and crashes when I click 'New Game'.

**Comment by Herick75** [comment]
Sorry for the delay, you can move games to Disk C for faster reading speed, you can also use chroot mode if you have root access for better experience
