### ISSUE TITLE
Como desisntala

### ISSUE THREAD

**Issue by Osamexx** [Herick75/Box4Droid#4]
Mano como desisntala isso

**Comment by headshot2017** [comment]
i didn't see uninstall instructions but i figured something out myself by typing these commands into termux:
```bash
rm -rf ~/ubuntu-fs
rm ~/../usr/bin/x11
rm ~/../usr/bin/start-box86
```

**Comment by Herick75** [comment]
Para uma instalação limpa, é só você apagar os dados do Termux, você também pode seguir as instruções que o cara mandou aí encima,mas no geral é só isso.
