### ISSUE TITLE
*Não é um problema,é apenas uma pergunta*

### ISSUE THREAD

**Issue by SombraShadow** [Herick75/Box4Droid#45]
Eu tô faz tempo com o Script do Ilya instalado,pq eu tô com Android 11 (que deixou de ser compatível) e agora,vi que seu rootfs atualizou.
Ele pode ser instalado em Android 11? (proot)
E eu vou precisar excluir o rootfs do Ilya para instalar este?

**Comment by Herick75** [comment]
Você pode instalar normalmente no seu Android 11,testei em um Moto G8 com Android 10(Snapdragon 665) e funcionou perfeitamente, inclusive os drivers para Adreno 610 que compilei.Você não precisa remover o script do Ilya, você pode ter os dois juntos.Caso você utilizar a VirGL, infelizmente tive que remover temporariamente.

**Comment by SombraShadow** [comment]
Ok,valeu mano :)
