### ISSUE TITLE
Error when try running games

### ISSUE THREAD

**Issue by JonJonesBR** [Herick75/Box4Droid#5]
I got this error when try to run any game: ./ptrace/user.h:46: word_t convert_user_offset(word_t): assertion "0" failed
proot warning: signal 6 received from process 6083

**Comment by JonJonesBR** [comment]
Check my screen:
![Screenshot_2023-04-06-21-46-47-033_com termux](https://user-images.githubusercontent.com/68039931/230518399-3363f6ae-d007-434e-9147-0fcbaf323ffb.jpg)

**Comment by headshot2017** [comment]
this happened to me with Sonic Adventure DX

**Comment by Herick75** [comment]
It seems that the error is related to the Proot, a possible solution is to use the proot-distro (which I'm already doing the tests and will release soon), or if not, just using the chroot, which requires root access to work .

**Comment by Herick75** [comment]
Hello,New version released,please update :)
