### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by ghost** [Herick75/Box4Droid#50]
After installation and running x11 and box-86, x11 just shows a black screen with the x cursor.

**Comment by Herick75** [comment]
You can try to use the old version of termux-x11, you can download it from the releases tab, you can also start Box4Droid and go to 3>6>use old termux-x11, there is the link to download the old version, copy it and paste in your browser and install, do not forget to activate this option

**Comment by ghost** [comment]
@Herick75 thank you, that fixed that Problem.👍 But now box64droid shows blackscreen, that worked on the new x11 😭😂
