### ISSUE TITLE
É preciso instalar uma versão do DXVK na primeira vez que iniciar?

### ISSUE THREAD

**Issue by SombraShadow** [Herick75/Box4Droid#8]
Eu já testei usando a dxvk 2.0,mas aí eu vi no Discord do Exagear international  que as dxvk 2.0+ precisam da Wine 8.1+.
Bom,se é preciso instalar uma Dxvk antes de iniciar um jogo,qual eu instalo?

**Comment by Herick75** [comment]
Olá, não é precisa instalar,o Rootfs já vem configurado com a DXVK 2.1,e essa versão é compatível com as versões da Wine a partir da 7.1, então todas as versões da DXVK são compatíveis com a Wine 7.1

**Comment by SombraShadow** [comment]
Ok,valeu mano tmj :)

**Comment by Herick75** [comment]
De nada :)
